9월 13일 수요일

### 1530 ~

In [ ]:
import array
data = array.array('b', [1, 2, 3])
dir(data) # __getitem__, __len__이 있으므로 sequence 데이터 타입
# Type code
## 'b' 

In [ ]:
a= [1, 2, 3, 4, 5]
b = [4, 5, 6, 7, 8]
# Q. a와 b의 값들을 하나씩 곱해주려면

# 1) 반복문 + zip으로
for x, y in zip(a,b):
	print(x * y)

In [ ]:

a= list(range(1000000))

In [ ]:
%%timeit
temp = []
for x in a:
	temp.append(x*x)

In [ ]:
%%timeit
import numpy as np
np.array(a) * np.array(a) # 벡터 간의 연산

In [ ]:
import tensorflow as tf

xx = tf.constant([1 , 2, 3])
xx.__class__

In [ ]:
import inspect
file_path = inspect.getfile(xx.__class__)

In [ ]:
with open(file_path, 'r', encoding='utf-8') as file:
    content = file.read()
    print(content)

In [42]:
array.array('b', [1, 2, 3]) 

array('b', [1, 2, 3])

In [41]:
b = array.array('b', [1, 2, 3]) # 파이썬의 array는 데이터 형식을 먼저 지정해줘야 한다 ('b')
b #

array('b', [1, 2, 3])

In [44]:
class X():
	def __repr__(self):
		return 'repr'
	def __str__(self):
		return 'str'

x = X()
print(x) # print하면 __str__이 실행
x # 그냥 부르면 __repr__이 실행

str


repr

In [45]:
a = np.array([1, 2, 3])
type(a)
#

# 클래

numpy.ndarray

In [52]:
b = np.ndarray((2, 3))
b

array([[4.63939877e-308, 5.64938534e+036, 1.78409531e+046],
       [4.32950182e-035, 8.72433218e-026, 1.57234264e-063]])

In [53]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
import numpy as np


a = np.array([[1, 2, 3], [ 4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
np.sctypeDict["i1"]

KeyError: 'f1'

In [68]:
a = np.array([[1, 2, 3], [ 4, 5, 6]], dtype = 'i1') #int8의 약자

a, a.shape, a.dtype # 제일 중요하다

# te

(array([[1, 2, 3],
        [4, 5, 6]], dtype=int8),
 (2, 3),
 dtype('int8'))

In [78]:
data = np.array([[[1],[2], [3]], [[3], [4], [6]]])
data.shape , data.ndim, data.items()

AttributeError: 'numpy.ndarray' object has no attribute 'items'