### ...의 용법

In [ ]:
# ...
print(...) #....__str__()가 Ellipss
type(...) # 파이썬에서 미리 정의된 클래스는 카멜 방식 X, 모두 소문자 -> 하나의 값이다



In [ ]:
# 부모 찾는 방법 (2)
type(...).__bases__ # 
type(...).mro() #

In [ ]:
# ...는 T/F 뭘까? 파이썬은 존재론적으로 보기
if ...:
    print('a')
else :
    print('b')

In [ ]:
# pass의 용법 : 함수의 구문이 없을 때 pass를 쓴다
def x():
    pass

def y():
    ...

a = y()
a

# pass 대신 ...을 쓸 수 있다.

In [ ]:
a = None
b = ...

In [ ]:
None == False # None은 아무것도 없는 것, False는 0을 의미한다

In [ ]:
if 0 == False:
    print(" False의 값은 0이다")

if None: pass
else : print("None은 False를 의미한다")

In [ ]:
import numpy as np
x = np.array([[1,2,3], [4, 5, 6]])

In [ ]:
x[0], x[[0]]

In [ ]:
# 이차원은 2가지 값을 넣어야 한다.
print(x[0][:])  #
print(x[0, :])  # 다르게 표현한 것
print(x[0]) # 두번째 값을 생략한 것

In [ ]:
print(x[:, :]) # 모든 행과 모든 열
print(x[...]) # ...으로 해결할 수 있다.

In [ ]:
xx = np.arange(24).reshape(2, 3, 4)

In [ ]:
# 4567을 뽑기
print(xx[0, 1, :])
print(xx[0 , 1]) # :을 생락햘 수 있다
# 1 ~ 11 모두 뽑기
print(xx[0])
print(xx[0, ...]) # ...으로 :을 생략 가능

# 첫번째 열만 뽑기 
xx[:, :, 0]
xx[..., 0]

In [ ]:
# ... 과 혼동 되는 None

x[None] # 범위에 없는 것을 출력하면 IndexError가 나온다..
x[1:100] # Slice에서는 범위에 없어도 에러가 없다. -> 100까지 slicing 해도 에러가 안나옴.

In [ ]:
y = [1, 2, 3, 4]
y[None] # 오류


In [55]:
xx[None]  # 차원이 늘어난다

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]])

In [59]:
# 2차원을 3차원으로 바꾸는 방법은 세가지가 존재 한다

print(xx[None, ...])
print("_____________")
print(xx[:, None, :])
print("_____________")
print(xx[..., None])

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]
_____________
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]]


 [[[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]
_____________
[[[[ 0]
   [ 1]
   [ 2]
   [ 3]]

  [[ 4]
   [ 5]
   [ 6]
   [ 7]]

  [[ 8]
   [ 9]
   [10]
   [11]]]


 [[[12]
   [13]
   [14]
   [15]]

  [[16]
   [17]
   [18]
   [19]]

  [[20]
   [21]
   [22]
   [23]]]]


In [63]:
# np.newaxis

np.newaxis == None 

x[np.newaxis] # np.newaxis == None 이기 때문에 np.newaxis를 넣어도 차원을 늘려준다. 

array([[[1, 2, 3],
        [4, 5, 6]]])

In [75]:
print(x.shape)
# 처음에 차원 추가 : 1, 2, 3
print(x[None].shape)
print(x[None, :].shape)
# 2, 1, 3
print(x[:, None].shape)
print(x[:, None, :].shape)
# 2, 3, 1
print(x[..., None].shape)
print(x[:, : , None].shape)


# 기본 메모리 공간은 float32

(2, 3)
(1, 2, 3)
(1, 2, 3)
(2, 1, 3)
(2, 1, 3)
(2, 3, 1)
(2, 3, 1)


In [86]:
# 연산자에 대응하는 메소드가 있다

y = [1, 2, 3, 4]

print(y[1:3])
print(y[slice(3)])


[2, 3]
[1, 2, 3]


(object,)

In [92]:
'__iter__' in dir(xx) # array에 __iter__가 있으므로 for 문에 넣을 수 있다(duck typing)
print(xx.shape)
for i in xx :
    print(i, "_") # 가장 앞에 있는 차원을 기준으로 돌린다 (2, 3, 4) -> (3, 4) 사이즈로 2번

(2, 3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] _
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] _


In [97]:
x = enumerate([ 'a', 'b','c', 'd'])
list(x)

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd')]

In [129]:
# 값을 하나씩 뽑아서 돌리기 -> np.ndenumerate (multi dimensional index iterator)
for i in np.ndenumerate(xx):
    print(i, '=')

# 컴퓨터에는 실제로 값이 일렬로 저장되어 있다

((0, 0, 0), 0) =
((0, 0, 1), 1) =
((0, 0, 2), 2) =
((0, 0, 3), 3) =
((0, 1, 0), 4) =
((0, 1, 1), 5) =
((0, 1, 2), 6) =
((0, 1, 3), 7) =
((0, 2, 0), 8) =
((0, 2, 1), 9) =
((0, 2, 2), 10) =
((0, 2, 3), 11) =
((1, 0, 0), 12) =
((1, 0, 1), 13) =
((1, 0, 2), 14) =
((1, 0, 3), 15) =
((1, 1, 0), 16) =
((1, 1, 1), 17) =
((1, 1, 2), 18) =
((1, 1, 3), 19) =
((1, 2, 0), 20) =
((1, 2, 1), 21) =
((1, 2, 2), 22) =
((1, 2, 3), 23) =


In [133]:
# stride
x = np.array([[1, 2, 3], [ 4, 5, 6]])
x.strides # 메모리의 간격을 알려준다 
# 12, 4 : 12만큼 전진하면 다음 행으로, 4만큼 더하면 다음 열로 이동할 수 있다. (실제 메모리에서의 구성)
# axis의 개념으로 메모리의 거리로 접근하면 속도가 매우 빠르다

(12, 4)

In [182]:
a = np.arange(24).reshape(4, 6)
a.sum() # 모든 값의 합
 # axis = 0의 의미 => 첫번째 차원을 제거하고 나머지 차원으로만 표현하라.
print(a)
print("_______")
print(a.shape)
print("_______")
print(a.sum(axis = 0)) # 첫번째 차원을 제거하고 더한다
print("_______")
print(a.sum(axis = 1)) # 두번째 차원을 제거하고 더한다 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
_______
(4, 6)
_______
[36 40 44 48 52 56]
_______
[ 15  51  87 123]


In [156]:
test = np.array([[70,80], [80, 90], [95, 50]])
print(test)
print(test.sum(axis= 0)) # array([245, 220])
print(test.sum(axis= 1)) # array([150, 170, 145])


[[70 80]
 [80 90]
 [95 50]]
[245 220]
[150 170 145]


In [170]:
a[0][4]

4

In [162]:
a = np.arange(24).reshape(4, 6)
print(a)
print("_______________")
print(a.shape)
print("_______________")
print(a.sum(axis = 0))
print("_______________")
print(a.sum(axis = 1))



[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
_______________
(4, 6)
_______________
[36 40 44 48 52 56]
_______________
[ 15  51  87 123]


IndexError: index 4 is out of bounds for axis 0 with size 4

In [177]:
print(xx)
xx.shape

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


(2, 3, 4)

In [175]:
xx.mean(axis = 0)

array([[ 6.,  7.,  8.,  9.],
       [10., 11., 12., 13.],
       [14., 15., 16., 17.]])

In [172]:
xx.mean(axis = 1)

array([[ 4.,  5.,  6.,  7.],
       [16., 17., 18., 19.]])

In [176]:
xx.mean(axis = 2)

array([[ 1.5,  5.5,  9.5],
       [13.5, 17.5, 21.5]])

In [195]:
# nditer
t = np.nditer(xx) # n차원 iterator로 변환하기
b = xx.flat


In [204]:
next(t) # array의 순서를 출력한다. array가 붙어서 나와서 잘 사용안한다. 

array(5)

In [202]:
next(b) # data.flat -> 순서를 바로 출력

6

In [205]:
xx.flatten() # n차의 데이터를 1차로 바꾼다. 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [206]:
xx.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [210]:
a = xx.flatten()
a.reshape(3, 8)
a.reshape((3, 8)) # 원래는 shape에 하나의 튜플을 입력해야 하지만, 오류가 많아서 괄호를 생략해도 괜찮게 함

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [215]:
a.reshape((3, 8), order = 'C') # 

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [216]:
a.reshape((3, 8), order = 'F')

array([[ 0,  3,  6,  9, 12, 15, 18, 21],
       [ 1,  4,  7, 10, 13, 16, 19, 22],
       [ 2,  5,  8, 11, 14, 17, 20, 23]])

In [217]:
a.reshape(4, -1) # 첫번째 차원을 결정하면 두번째는 -1을 넣으면 알아서 계산해준다. 
# resh

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [218]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [219]:
a.resize(4, 5, refcheck= False) #4*5로 만들고 남는 값은 잘라버림

In [223]:
x = np.array([1, 2, 3, 4])
x.size

4

In [221]:
a.size


20

### 1700

In [232]:
a = np.array([[1,2] , [3, 4]])
b = np.array([[1,2] , [3, 4]])

print(a), 
print("__________")
print(b)
print("__________")
print(np.concatenate((a, b))) # defalut는 행을 붙이기
print("__________")
print(np.concatenate((a, b), 1)) # default는 열로 붙이기

[[1 2]
 [3 4]]
__________
[[1 2]
 [3 4]]
__________
[[1 2]
 [3 4]
 [1 2]
 [3 4]]
__________
[[1 2 1 2]
 [3 4 3 4]]


In [233]:
np.column_stack((a, b))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [239]:
 # 대괄호 : indexer (pandas에서 또 나옴)
print(np.c_[a, b]) # column끼리 붙이기
print("_______")
print(np.r_[a, b]) # row 끼리 붙이기 

[[1 2 1 2]
 [3 4 3 4]]
_______
[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [247]:
print(np.r_[a,b ])
print("__________")
print(np.r_[a,b ].shape)
print("__________")
print(np.stack((a,b)))
print("__________")
np.stack((a,b)).shape

[[1 2]
 [3 4]
 [1 2]
 [3 4]]
__________
(4, 2)
__________
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
__________


(2, 2, 2)

In [249]:

print(a)
print(np.stack(a))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [ ]:
func_list = ["dstack"]

In [255]:
x = np.hstack((a,b))
print(x)
print(x.shape)

[[1 2 1 2]
 [3 4 3 4]]
(2, 4)


In [253]:
x = np.vstack((a,b))
print(x)
print(x.shape)

[[1 2]
 [3 4]
 [1 2]
 [3 4]]
(4, 2)


In [256]:
x = np.dstack((a,b))
print(x)
print(x.shape)

[[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]]
(2, 2, 2)


In [264]:
data = np.arange(24).reshape((2, 3, 4))
print(data)
print('_________')
print(data.T)
data.T.shape

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
_________
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


(4, 3, 2)

In [266]:
np.transpose(data, [2, 0 , 1])

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [270]:
x = np.swapaxes(data, 0, 2) # 0과 2번째 axis를 전환한다. 
print(data)
print(data.shape)
print("_____________")
print(x)
print(x.shape) # 

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
_____________
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
(4, 3, 2)


In [269]:
x = np.moveaxis(data, 0, 2) # 첫번째 축을 3번째 축으로 보내기 
print(data)
print(data.shape)
print("_____________")
print(x)
print(x.shape) # 3 * 340 * 340 -> 340 * 3 * 3으로 옮기고 싶을 떄 

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
_____________
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]
(3, 4, 2)


In [ ]:
np.swapaxis(data, 0, 2)

